hydra:
  run:
    dir: ${cache_path}/${task}/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: llama-3.1-8b
  - estimators: cot_estimators
  - stat_calculators: default_calculators
  - base_processing_gsm8k
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: false
task: qa

dataset: ['denis1699/gsm8k_reasoning']
text_column: question
label_column: answer
train_split: train
eval_split: test
few_shot_prompt: null
max_new_tokens: 512
load_from_disk: false
trust_remote_code: false


subsample_eval_dataset: -1

generation_metrics: null

generation_params:
  generate_until:
    - "Question:"

ignore_exceptions: false

batch_size: 1

seed:
    - 1
